--Table to configure game room types
CREATE TABLE IF NOT EXISTS GAME_ROOM_TYPE (
    GAME_ROOM_TYPE_ID NUMBER NOT NULL,
    GAME_ROOM_AMT NUMERIC(20)  NOT NULL,
    GAME_ROOM_SIZE NUMERIC(20)  NOT NULL,
    GAME_DESC VARCHAR2(100)  NOT NULL,
	CONSTRAINT PK_GAME_TYPE_ID Primary Key (GAME_ROOM_TYPE_ID)
);

INSERT INTO GAME_ROOM_TYPE (GAME_ROOM_TYPE_ID,GAME_ROOM_AMT,GAME_ROOM_SIZE, GAME_DESC) VALUES (1,10,10,'10 Player room with entry fee of 10');
INSERT INTO GAME_ROOM_TYPE (GAME_ROOM_TYPE_ID,GAME_ROOM_AMT,GAME_ROOM_SIZE, GAME_DESC) VALUES (2,10,100,'10 Player room with entry fee of 100');
INSERT INTO GAME_ROOM_TYPE (GAME_ROOM_TYPE_ID,GAME_ROOM_AMT,GAME_ROOM_SIZE, GAME_DESC) VALUES (3,10,1000,'10 Player room with entry fee of 1000');

--Table to store GAME room info
CREATE TABLE IF NOT EXISTS GAME_INFO (
    GAME_ID UUID NOT NULL,
    GAME_ROOM_TYPE_ID NUMBER,
    GAME_DATE DATE not null default CURRENT_TIMESTAMP,
	FIRST_POS VARCHAR2(30),
	SECOND_POS VARCHAR2(30),
	THIRD_POS VARCHAR2(30),
	GAME_STATUS VARCHAR2(30),
	CONSTRAINT PK_GAME_ID Primary Key (GAME_ID),
	CONSTRAINT FK_GAME_TYPE_ID  FOREIGN KEY (GAME_ROOM_TYPE_ID) REFERENCES GAME_ROOM_TYPE(GAME_ROOM_TYPE_ID)
);

--Table to store player game mapping
CREATE TABLE IF NOT EXISTS PLAYER_GAME_INFO (
    PLAYER_ID VARCHAR2(30) NOT NULL,
    TOKEN_ID VARCHAR2(30) NOT NULL,
    CONSTRAINT PK_TOKEN_ID Primary Key (TOKEN_ID)
);

CREATE TABLE IF NOT EXISTS PLAYER_GAME (
    GAME_ID UUID NOT NULL,
    TOKEN_ID VARCHAR2(30) NOT NULL,
    CONSTRAINT PK_GAME_TOKEN_ID PRIMARY KEY (GAME_ID,TOKEN_ID),
	CONSTRAINT FK_GAME_ID  FOREIGN KEY (GAME_ID) REFERENCES GAME_INFO(GAME_ID),
	CONSTRAINT FK_TOKEN_ID FOREIGN KEY (TOKEN_ID) REFERENCES PLAYER_GAME_INFO(TOKEN_ID)
);

--Order of table drop
--drop table PLAYER_GAME_INFO;
--drop table GAME_INFO;
--drop table GAME_ROOM_TYPE;
--drop table GAME_STATUS_TYPE;
